name: Deploy Model Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd ./terraform/lambda
        terraform init

    - name: Terraform Validate
      run: |
        cd ./terraform/lambda
        terraform validate

    - name: Terraform Plan
      run: |
        cd ./terraform/lambda
        terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: |
        cd ./terraform/lambda 
        terraform apply -auto-approve