name: Deploy Model Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd ./terraform/lambda
        terraform init

    - name: Import Existing Resources
      run: |
        cd ./terraform/lambda
        terraform import aws_ecr_repository.tdp_model_ecr tdp/the-docker-playbook-model
        terraform import aws_iam_role.tdp_lambda_role tdp_model_execution_role
        terraform import aws_iam_policy.s3_access_policy arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/tdp_model_s3_access_policy
        terraform import aws_iam_policy.ecr_access_policy arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/tdp_model_ecr_access_policy


    - name: Terraform Validate
      run: |
        cd ./terraform/lambda
        terraform validate

    - name: Terraform Plan
      run: |
        cd ./terraform/lambda
        terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: |
        cd ./terraform/lambda 
        terraform apply -auto-approve